// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJKGRQeXpSdGt62l93m-V4nre-Bv_1YRc',
    appId: '1:808136814093:web:ab86713776469511f5af44',
    messagingSenderId: '808136814093',
    projectId: 'safe-sprout',
    authDomain: 'safe-sprout.firebaseapp.com',
    storageBucket: 'safe-sprout.appspot.com',
    measurementId: 'G-J4XT824X40',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmsyK3KKIN6SflBcGTsDB9OKHaCbn9S7o',
    appId: '1:808136814093:android:61707f49916218a7f5af44',
    messagingSenderId: '808136814093',
    projectId: 'safe-sprout',
    storageBucket: 'safe-sprout.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG2-hP0GCzIGMzUlVJ7zD2IiY0yVba_v8',
    appId: '1:808136814093:ios:9e82643634824469f5af44',
    messagingSenderId: '808136814093',
    projectId: 'safe-sprout',
    storageBucket: 'safe-sprout.appspot.com',
    iosBundleId: 'com.example.diceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG2-hP0GCzIGMzUlVJ7zD2IiY0yVba_v8',
    appId: '1:808136814093:ios:49ac0414cac2eeb2f5af44',
    messagingSenderId: '808136814093',
    projectId: 'safe-sprout',
    storageBucket: 'safe-sprout.appspot.com',
    iosBundleId: 'com.example.diceApp.RunnerTests',
  );
}
